#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::too_many_arguments)]
// `ffi.rs` is bindgen output (regenerated by `update.sh`), and bindgen copies
// the C header's Doxygen prose into `#[doc = ...]` verbatim. That prose uses
// `[in]`, `[out]`, `[unused]` and `[unsupported]` as parameter-direction
// markers, which rustdoc then reads as intra-doc links to Rust items that do
// not exist — 142 warnings, none of them actionable. Allowed here rather than
// escaped in `ffi.rs` because any edit to a generated file is lost the next
// time it is regenerated.
#![allow(rustdoc::broken_intra_doc_links)]

include!("ffi.rs");
