#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2025 Au-Zone Technologies
# SPDX-License-Identifier: Apache-2.0
"""
YOLOv8 detection + instance segmentation on ARA-2 NPU.

End-to-end inference using the same 3-step postprocessing pipeline as
the Rust example (examples/yolov8.rs):

    JPEG → [codec] decode → [GPU] letterbox resize → PlanarRGB → [NPU] infer
                                                         │
                                                 ┌───────┴────────┐
                                            boxes/scores      proto data
                                                 │                │
                                       [1] decode_proto           │
                                         NMS + dequant            │
                                                 │                │
                                       [2] materialize_masks ─────┘
                                         CPU dot-product
                                         coeff × protos → bitmaps
                                                 │
                                       [3] draw_decoded_masks
                                         GL overlay onto canvas

Usage:
    Run with ``--help`` for the full flag reference (generated by argparse).

Models:
    Official pre-trained models are published in the EdgeFirst model zoo on
    Hugging Face:

      Detection:    https://huggingface.co/EdgeFirst/yolov8-det
      Segmentation: https://huggingface.co/EdgeFirst/yolov8-seg

    Each repository ships one directory per target; the ARA-2 builds are the
    int16 ``.dvm`` exports under ``ara240/``, in n/s/m sizes.

      curl -LO https://huggingface.co/EdgeFirst/yolov8-det/resolve/main/ara240/yolov8n-det-int16.dvm
      curl -LO https://huggingface.co/EdgeFirst/yolov8-seg/resolve/main/ara240/yolov8n-seg-int16.dvm

    Every export embeds an ``edgefirst.json`` schema and the class
    ``labels.txt`` in a ZIP trailer appended to the ``.dvm``. That schema is
    where the per-output ``normalized`` flag and named ``dshape`` come from —
    the NPU runtime reports neither, and a model emitting pixel-space boxes
    is misread without them. An export with no trailer still runs, falling
    back to the built-in COCO labels and :func:`canonical_dshape`.

    This example pins ``DecoderVersion.Yolov8``, so it decodes the
    ``yolov8-det`` and ``yolov8-seg`` repositories.

Requirements:
    edgefirst-ara2  edgefirst-codec>=0.31  edgefirst-decoder>=0.31
    edgefirst-image>=0.31  numpy

    The EdgeFirst HAL ships as one package per library rather than a single
    ``edgefirst-hal`` wheel; ``edgefirst-tensor`` arrives as a dependency of
    the other three. Each is imported under the shared ``edgefirst.``
    namespace, so the prefix on a name says which library it comes from.
"""

from __future__ import annotations

import argparse
import math
import os
import sys
import time

import numpy as np

import edgefirst.codec as ef_codec
import edgefirst.decoder as ef_decoder
import edgefirst.image as ef_image
import edgefirst.tensor as ef_tensor
import edgefirst_ara2 as ara2


# ── Helpers ───────────────────────────────────────────────────────────────────


def normalize_shape(raw: tuple[int, int, int]) -> list[int]:
    """Normalize an ARA-2 output shape for the EdgeFirst decoder.

    ARA-2 always reports 3D shapes [C, H, W]. For logically 2D outputs
    (e.g., scores [80, 8400]), the shape is padded as [80, 8400, 1].
    We strip trailing 1s and prepend batch=1 for the decoder.

      [80, 8400, 1]  → [1, 80, 8400]     (scores)
      [4, 8400, 1]   → [1, 4, 8400]      (boxes)
      [32, 160, 160] → [1, 32, 160, 160] (protos)
    """
    shape = list(raw)
    while len(shape) > 1 and shape[-1] == 1:
        shape.pop()
    shape.insert(0, 1)
    return shape


def compute_letterbox(
    src_w: int, src_h: int, dst_w: int, dst_h: int
) -> tuple[float, float, float, float]:
    """Normalized letterbox rect for the fit ``ImageProcessor.convert`` applies.

    ``convert(src, dst, letterbox=(r, g, b, a))`` fits the source into the
    destination preserving aspect ratio and pads the remainder with the given
    colour, so the caller no longer passes a destination rectangle. The same
    placement still has to be described in normalized model-input coordinates
    for ``materialize_masks`` and ``draw_decoded_masks``, which map mask and
    box coordinates back to the original image.

    This mirrors the HAL's own ``letterbox_rect``: the long axis fills the
    destination exactly, the short axis is rounded half-away-from-zero, and
    the result is centred. Reproducing it here (rather than re-deriving a
    plausible fit) is what keeps the overlay aligned with the pixels the GPU
    actually rendered.

    Returns:
        Normalized ``(x0, y0, x1, y1)`` in model-input space.
    """
    src_aspect = src_w / src_h
    dst_aspect = dst_w / dst_h
    if src_aspect > dst_aspect:
        new_w, new_h = dst_w, max(1, math.floor(dst_w / src_aspect + 0.5))
    else:
        new_w, new_h = max(1, math.floor(dst_h * src_aspect + 0.5)), dst_h
    x = (dst_w - new_w) // 2
    y = (dst_h - new_h) // 2
    return (x / dst_w, y / dst_h, (x + new_w) / dst_w, (y + new_h) / dst_h)


def unletterbox(
    box, letterbox: tuple[float, float, float, float], img_w: int, img_h: int
) -> tuple[float, float, float, float]:
    """Map one decoded box back onto the original image, in pixels.

    The decoder reports coordinates normalised to the *letterboxed model
    input* — a 1280x720 frame fitted into 640x640 leaves grey bands top and
    bottom, and a box's ``y`` is measured against the padded 640, not against
    the 720. ``letterbox`` (from :func:`compute_letterbox`) says where the real
    content sits inside that frame, so removing the offset and rescaling by
    the content's extent recovers original-image coordinates.

    ``draw_decoded_masks`` is handed the same ``letterbox`` and does this
    internally; this is the arithmetic needed to *print* the boxes so they
    agree with what was drawn.
    """
    lx0, ly0, lx1, ly1 = letterbox
    span_x = max(lx1 - lx0, 1e-9)
    span_y = max(ly1 - ly0, 1e-9)
    x1 = min(max((float(box[0]) - lx0) / span_x, 0.0), 1.0) * img_w
    y1 = min(max((float(box[1]) - ly0) / span_y, 0.0), 1.0) * img_h
    x2 = min(max((float(box[2]) - lx0) / span_x, 0.0), 1.0) * img_w
    y2 = min(max((float(box[3]) - ly0) / span_y, 0.0), 1.0) * img_h
    return x1, y1, x2, y2


def output_dtype(bpp: int, signed: bool) -> str:
    """Map ARA-2 output tensor bpp/signed flags to an EdgeFirst dtype string."""
    if bpp == 1:
        return "int8" if signed else "uint8"
    return "int16" if signed else "uint16"


def strip_trailing_ones(raw) -> list[int]:
    """Strip trailing 1s from a metadata shape.

    Metadata declares shapes with the leading batch and any trailing
    ``padding`` axes; the NPU runtime strips trailing 1s before returning the
    per-output shape. Normalising both sides the same way lets a runtime shape
    be matched to its ``OutputSpec``.
    """
    shape = [int(d) for d in raw]
    while len(shape) > 1 and shape[-1] == 1:
        shape.pop()
    return shape


def index_metadata_by_shape(metadata) -> dict[tuple[int, ...], object]:
    """Index a model's metadata outputs by their normalised shape.

    The runtime reports shape and quantization; ``edgefirst.json`` inside the
    ``.dvm`` adds the semantics the runtime cannot know — the named ``dshape``
    and, for box outputs, whether coordinates are already normalised. Older
    ``.dvm`` files carry neither, and the caller falls back accordingly.
    """
    if metadata is None:
        return {}
    return {tuple(strip_trailing_ones(o.shape)): o for o in metadata.outputs}


DIM_NAMES = {
    "batch": "Batch",
    "height": "Height",
    "width": "Width",
    "num_classes": "NumClasses",
    "num_features": "NumFeatures",
    "num_boxes": "NumBoxes",
    "num_protos": "NumProtos",
    "num_anchors_x_features": "NumAnchorsXFeatures",
    "padding": "Padding",
    "box_coords": "BoxCoords",
}


def metadata_dshape(
    spec, shape: list[int]
) -> list[tuple[ef_decoder.DimName, int]] | None:
    """Convert an ``OutputSpec.dshape`` into decoder ``DimName`` pairs.

    Returns ``None`` when the metadata carries no ``dshape`` (or names an axis
    this build does not recognise), leaving the caller on
    :func:`canonical_dshape`.

    Two fix-ups mirror the Rust example: trailing dims past the rank of
    *shape* are dropped (metadata may declare a ``padding=1`` axis the NPU
    strips), and a ``mask_coefs`` output declaring ``num_features`` on its
    channel axis is corrected to ``num_protos`` — some converters emit the
    wrong name and the decoder's role validator rejects it.
    """
    if spec is None or not spec.dshape:
        return None
    pairs = list(spec.dshape)[: len(shape)]
    is_mask_coefs = spec.output_type == "mask_coefs"
    out = []
    for name, extent in pairs:
        if is_mask_coefs and name == "num_features":
            name = "num_protos"
        attr = DIM_NAMES.get(name)
        if attr is None:
            return None
        out.append((getattr(ef_decoder.DimName, attr), extent))
    return out


def canonical_dshape(role: str, shape: list[int]) -> list[tuple[ef_decoder.DimName, int]]:
    """Name each dimension of an Ultralytics output tensor.

    An anonymous ``shape=`` leaves the decoder to guess which axis carries
    what, and for the rank-4 proto tensor it guesses wrong: ``[1, 32, 160,
    160]`` is read as trailing-channel, and ``materialize_masks`` then rejects
    the coefficients as "``[N, 32]`` incompatible with protos ``[32, 160,
    160]``".  Naming the dimensions removes the guess — this mirrors
    ``canonical_dshape`` in the Rust example (``examples/yolov8.rs``), which
    supplies the same names when the DVM metadata carries no ``dshape``.

    Args:
        role: One of ``"protos"``, ``"boxes"``, ``"scores"``, or
            ``"mask_coefficients"``.
        shape: The batch-prefixed shape from ``normalize_shape``.

    Returns:
        ``[(DimName, extent), ...]``, one entry per dimension of *shape*.
    """
    d = ef_decoder.DimName
    names = {
        "protos": [d.Batch, d.NumProtos, d.Height, d.Width],
        "boxes": [d.Batch, d.BoxCoords, d.NumBoxes],
        "scores": [d.Batch, d.NumClasses, d.NumBoxes],
        "mask_coefficients": [d.Batch, d.NumProtos, d.NumBoxes],
    }[role]
    return list(zip(names, shape))


def _decoder_output(
    shape: list[int],
    quant,
    spec,
    n_proto_ch: int | None,
    input_dim: float,
) -> ef_decoder.Output:
    """Build the decoder ``Output`` for a single model output tensor.

    The role is inferred from *shape*; the named ``dshape`` comes from the DVM
    metadata when it carries one, otherwise from :func:`canonical_dshape`.

    Args:
        shape: Batch-prefixed runtime shape of this output.
        quant: Runtime quantization for this output.
        spec: ``OutputSpec`` from the DVM metadata, or ``None`` when the
            metadata does not describe this output.
        n_proto_ch: Prototype-channel count, or ``None`` for a detect-only
            model with no proto tensor.
        input_dim: Largest model input dimension.
    """
    qn, offset = quant.qn, quant.offset

    def dshape_for(role: str) -> list[tuple[ef_decoder.DimName, int]]:
        return metadata_dshape(spec, shape) or canonical_dshape(role, shape)

    if len(shape) == 4:
        # Proto tensor [1, 32, H, W]
        out = ef_decoder.Output.protos(
            dshape=dshape_for("protos"),
            decoder=ef_decoder.DecoderType.Ultralytics,
        )
        return out.with_quantization(qn, offset)

    if len(shape) == 3 and shape[1] == 4:
        # Box tensor [1, 4, N]. A spec-conforming export declares `normalized`,
        # and its coordinates are already in [0, 1] — use qn as-is. An older
        # export that declares nothing emits int-encoded pixel coordinates in
        # [0, input_dim], so the quantization scale is divided by input_dim to
        # bring them into the same range. Dividing unconditionally (as this
        # example used to) makes a modern model's boxes `input_dim` times too
        # small.
        normalized = spec.normalized if spec is not None else None
        scale = qn / input_dim if normalized is None and input_dim > 1 else qn
        out = ef_decoder.Output.boxes(
            dshape=dshape_for("boxes"),
            decoder=ef_decoder.DecoderType.Ultralytics,
        )
        out = out.with_quantization(scale, offset)
        return out.with_normalized(True if normalized is None else normalized)

    if n_proto_ch and len(shape) == 3 and shape[1] == n_proto_ch:
        # Mask coefficient tensor [1, 32, N]
        out = ef_decoder.Output.mask_coefficients(
            dshape=dshape_for("mask_coefficients"),
            decoder=ef_decoder.DecoderType.Ultralytics,
        )
        return out.with_quantization(qn, offset)

    # Score tensor [1, C, N]
    out = ef_decoder.Output.scores(
        dshape=dshape_for("scores"),
        decoder=ef_decoder.DecoderType.Ultralytics,
    )
    return out.with_quantization(qn, offset)


def build_decoder(
    shapes: list[list[int]],
    quants: list,
    specs: list,
    input_dim: float,
    threshold: float,
    iou: float,
) -> ef_decoder.Decoder:
    """Build an EdgeFirst Decoder from model output metadata.

    Output tensor roles are identified by shape:
      - Protos:             rank-4  [1, 32, H, W]
      - Boxes:              rank-3  [1,  4, N]  (shape[1] == 4)
      - Mask coefficients:  rank-3  [1, 32, N]  (shape[1] == n_proto_channels)
      - Scores:             rank-3  [1,  C, N]  (everything else)

    Each output is declared with a named ``dshape`` — from the DVM metadata
    when it carries one, otherwise :func:`canonical_dshape`.

    Args:
        shapes: Batch-prefixed runtime shapes from ``normalize_shape``.
        quants: Per-output runtime quantization from ``model.output_quants``.
        specs: Per-output ``OutputSpec`` from the DVM metadata, or ``None``
            for outputs the metadata does not describe.
        input_dim: Largest model input dimension.
        threshold: Minimum score to keep a detection.
        iou: IoU threshold for non-maximum suppression.
    """
    # Number of prototype channels (e.g., 32) from the rank-4 proto tensor.
    proto_shape = next((s for s in shapes if len(s) == 4), None)
    n_proto_ch = proto_shape[1] if proto_shape else None

    outputs = [
        _decoder_output(shape, quants[i], specs[i], n_proto_ch, input_dim)
        for i, shape in enumerate(shapes)
    ]

    return ef_decoder.Decoder.new_from_outputs(
        outputs,
        score_threshold=threshold,
        iou_threshold=iou,
        decoder_version=ef_decoder.DecoderVersion.Yolov8,
    )


# ── Benchmark stats ───────────────────────────────────────────────────────────


def _row(label: str, data: list[float]) -> None:
    a = np.array(data)
    print(f"  {label:<30} {a.mean():6.2f}  {a.min():6.2f}  {a.max():6.2f}  {a.std():6.2f}")


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="YOLOv8 detection + segmentation on ARA-2 NPU",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("model", help="Path to compiled .dvm model file")
    parser.add_argument("image", help="Path to input image (JPEG/PNG)")
    # Lower default (0.25) than yolov8_live.py (0.50): static-image inspection
    # benefits from surfacing lower-confidence detections for visual review.
    parser.add_argument("--threshold", type=float, default=0.25)
    parser.add_argument("--iou", type=float, default=0.45)
    parser.add_argument("--benchmark", type=int, default=0,
                        help="Run N iterations and print timing statistics")
    parser.add_argument("--save", action="store_true",
                        help="Save overlay image next to the input image")
    parser.add_argument(
        "--color-mode", default="class",
        choices=["class", "instance", "track"],
        help="Segmentation mask color assignment (default: class)",
    )
    parser.add_argument("--socket", default=ara2.DEFAULT_SOCKET)
    args = parser.parse_args()

    # Map --color-mode to the edgefirst-image ColorMode enum
    color_mode = {
        "class": ef_image.ColorMode.Class,
        "instance": ef_image.ColorMode.Instance,
        "track": ef_image.ColorMode.Track,
    }[args.color_mode]

    # ── 1. Read DVM metadata ─────────────────────────────────────────────
    # Each library reports its own version; they are released in lockstep.
    print(f"edgefirst-ara2 v{ara2.__version__}, "
          f"edgefirst-tensor v{ef_tensor.version()}, "
          f"edgefirst-codec v{ef_codec.version()}, "
          f"edgefirst-image v{ef_image.version()}, "
          f"edgefirst-decoder v{ef_decoder.version()}")
    metadata = ara2.read_metadata(args.model)
    labels = ara2.read_labels(args.model) or COCO_LABELS
    if metadata:
        print(f"Task: {metadata.task}, Classes: {len(labels)}")
        if metadata.compilation and metadata.compilation.ppa:
            ppa = metadata.compilation.ppa
            print(f"Target: {metadata.compilation.target}, "
                  f"IPS: {ppa.ips:.0f}, Power: {ppa.power_mw:.0f} mW")

    # ── 2. Connect to ARA-2 and load model ───────────────────────────────
    session = ara2.Session.create_via_unix_socket(args.socket)
    endpoints = session.list_endpoints()
    if not endpoints:
        print("No ARA-2 endpoints found. Is the proxy running?")
        sys.exit(1)

    endpoint = endpoints[0]
    stats = endpoint.dram_statistics()
    print(f"Endpoint: {endpoint.check_status()}, "
          f"DRAM: {stats.free_size / 1048576:.0f} / {stats.dram_size / 1048576:.0f} MB free")

    with endpoint.load_model(args.model) as model:
        model.allocate_tensors("dma")
        c, h, w = model.input_shape(0)
        input_dim = float(max(w, h))
        iq = model.input_quants(0)
        print(f"Input: {c}×{h}×{w} (CHW), dtype={'int8' if iq.is_signed else 'uint8'}")

        # ── 3. Build decoder from output tensor metadata ─────────────────
        # The runtime supplies shape and quantization; the DVM's
        # `edgefirst.json` adds the named dshape and the `normalized` flag.
        meta_by_shape = index_metadata_by_shape(metadata)
        shapes, quants, specs = [], [], []
        for i in range(model.n_outputs):
            shape = normalize_shape(model.output_shape(i))
            oq = model.output_quants(i)
            info = model.output_info(i)
            spec = meta_by_shape.get(tuple(shape))
            norm = spec.normalized if spec is not None else None
            print(f"  output[{i}]: {shape}  bpp={info.bpp}  "
                  f"qn={oq.qn:.6g}  signed={oq.is_signed}  normalized={norm}")
            shapes.append(shape)
            quants.append(oq)
            specs.append(spec)

        decoder = build_decoder(
            shapes, quants, specs, input_dim, args.threshold, args.iou
        )

        # ── 4. Decode source image into a DMA-BUF tensor ─────────────────
        # edgefirst-codec decodes into a buffer edgefirst-image allocated:
        # peek the header for the native geometry, allocate once, decode in
        # place. The decoder never converts — a colour JPEG lands as NV12.
        processor = ef_image.ImageProcessor()
        info = ef_codec.Tensor.peek_image_info_file(args.image)
        frame = processor.create_image(info.width, info.height, info.format)
        ef_codec.decode_file_into(frame, args.image)
        img_w, img_h = frame.width, frame.height
        print(f"Image: {img_w}×{img_h} (decoded as {info.format})")

        # The model input is converted straight from the native frame: the GPU
        # reads NV12 and writes PlanarRGB in one pass. Routing it through an
        # RGBA copy first costs a second conversion *and* shifts the result —
        # the extra chroma round trip moves boxes by up to ~20 px away from
        # the single-pass answer (which matches examples/yolov8.rs exactly).
        #
        # The overlay is a separate concern: `background=` must be the same
        # format as the canvas it composites into, so the display base layer
        # gets its own one-off RGBA conversion.
        background = processor.create_image(
            img_w, img_h, ef_image.PixelFormat.Rgba
        )
        processor.convert(frame, background)

        # ── 5. Import NPU input tensor and compute letterbox ──────────────
        # Letterbox-resize the frame → NPU input, preserving aspect ratio with
        # YOLO gray (114, 114, 114) padding. The same letterbox_norm is
        # later passed to materialize_masks and draw_decoded_masks so mask
        # coordinates are correctly mapped to output-image space.
        input_fd = model.input_tensor_fd(0)
        try:
            dst = processor.import_image(
                input_fd, w, h, ef_image.PixelFormat.PlanarRgb,
                dtype="int8" if iq.is_signed else "uint8",
            )
        finally:
            os.close(input_fd)

        letterbox_norm = compute_letterbox(img_w, img_h, w, h)

        # ── 6. Wrap output DMA-BUF tensors for zero-copy decode ──────────
        # These persist across iterations; model.run() updates the underlying
        # DMA memory in-place, so decode_proto always sees fresh data without
        # any CPU copy.
        output_tensors = []
        for i in range(model.n_outputs):
            fd = model.output_tensor_fd(i)
            # from_fd takes ownership of fd via OwnedFd (no dup) — do NOT close.
            t = ef_tensor.Tensor.from_fd(
                fd,
                shapes[i],
                output_dtype(model.output_info(i).bpp,
                             model.output_quants(i).is_signed),
            )
            output_tensors.append(t)

        # ── 7. Pre-allocate render canvas ────────────────────────────────
        # Blank DMA-BUF RGBA canvas at source-image resolution for the overlay.
        canvas = processor.create_image(img_w, img_h, ef_image.PixelFormat.Rgba)

        # ── 8. Warmup: prime GPU caches, JIT paths, EGL image bindings ───
        processor.convert(frame, dst, letterbox=(114, 114, 114, 255))
        model.run()
        _wb, _ws, _wc, _wp = decoder.decode_proto(output_tensors)
        _wm = processor.materialize_masks(_wb, _ws, _wc, _wp,
                                          letterbox=letterbox_norm) if _wp else []
        processor.draw_decoded_masks(canvas, _wb, _ws, _wc, seg=_wm,
                                     background=background,
                                     letterbox=letterbox_norm,
                                     color_mode=color_mode)

        # ── 9. Single-shot timed run ──────────────────────────────────────
        t0 = time.monotonic()
        processor.convert(frame, dst, letterbox=(114, 114, 114, 255))
        pre_ms = (time.monotonic() - t0) * 1000

        t1 = time.monotonic()
        timing = model.run()
        inf_ms = (time.monotonic() - t1) * 1000

        # Step 1 — Decode: NMS + dequant on raw NPU output tensors
        t2 = time.monotonic()
        boxes, scores, classes, proto_data = decoder.decode_proto(output_tensors)
        dec_ms = (time.monotonic() - t2) * 1000

        # Step 2 — Materialize: CPU dot-product coeff × protos → bitmaps.
        # No-op for detection-only models (proto_data is None).
        #
        # An int8 segmentation model needs edgefirst-image >= 0.31.0: earlier
        # releases dropped the prototype tensors' quantization crossing from
        # edgefirst.decoder, and this raised "I8 mask_coefficients require
        # quantization metadata".
        t3 = time.monotonic()
        masks = (processor.materialize_masks(boxes, scores, classes, proto_data,
                                             letterbox=letterbox_norm)
                 if proto_data else [])
        mat_ms = (time.monotonic() - t3) * 1000

        # Step 3 — Draw: GL-accelerated overlay of bitmaps onto canvas
        t4 = time.monotonic()
        processor.draw_decoded_masks(canvas, boxes, scores, classes,
                                     seg=masks, background=background,
                                     letterbox=letterbox_norm,
                                     color_mode=color_mode)
        draw_ms = (time.monotonic() - t4) * 1000

        # ── 10. Print results ─────────────────────────────────────────────
        n_det = len(scores)
        print(f"\n--- Detections ({n_det}) ---")
        for i in range(n_det):
            cls = int(classes[i])
            name = labels[cls] if cls < len(labels) else f"class_{cls}"
            x1, y1, x2, y2 = unletterbox(boxes[i], letterbox_norm, img_w, img_h)
            print(f"  {name:>12} ({cls:2}): {scores[i]*100:5.1f}%  "
                  f"[{x1:.0f}, {y1:.0f}, {x2:.0f}, {y2:.0f}]")

        total = pre_ms + inf_ms + dec_ms + mat_ms + draw_ms
        print("\n--- Timing ---")
        print(f"  Preprocess:  {pre_ms:6.2f} ms")
        print(f"  Inference:   {inf_ms:6.2f} ms"
              f"  (npu: {timing.run_time_us/1000:.2f} ms,"
              f"  in: {timing.input_time_us/1000:.2f} ms,"
              f"  out: {timing.output_time_us/1000:.2f} ms)")
        print(f"  Decode:      {dec_ms:6.2f} ms")
        print(f"  Materialize: {mat_ms:6.2f} ms")
        print(f"  Draw:        {draw_ms:6.2f} ms")
        print(f"  Total:       {total:6.2f} ms  ({1000/total:.1f} FPS)")

        # ── 11. Save overlay ──────────────────────────────────────────────
        if args.save:
            base, _ = os.path.splitext(args.image)
            out_path = base + "_overlay.jpg"
            canvas.save_jpeg(out_path, 90)
            print(f"\n  Saved: {out_path}")

        # ── 12. Benchmark ─────────────────────────────────────────────────
        if args.benchmark > 0:
            _benchmark(
                model,
                processor=processor,
                frame=frame,
                background=background,
                dst=dst,
                canvas=canvas,
                decoder=decoder,
                output_tensors=output_tensors,
                letterbox_norm=letterbox_norm,
                n_iter=args.benchmark,
                color_mode=color_mode,
            )


def _benchmark(
    model: ara2.Model,
    *,
    processor: ef_image.ImageProcessor,
    frame: ef_image.Tensor,
    background: ef_image.Tensor,
    dst: ef_image.Tensor,
    canvas: ef_image.Tensor,
    decoder: ef_decoder.Decoder,
    output_tensors: list,
    letterbox_norm: tuple,
    n_iter: int,
    color_mode: ef_image.ColorMode,
) -> None:
    """Run N timed iterations and print per-stage statistics.

    Args:
        model: Loaded ARA-2 model to benchmark.
        processor: edgefirst-image ImageProcessor used for convert / draw.
        frame: Decoded source frame in its native format; converted to the
            model input on each iteration.
        background: RGBA copy of the frame at source resolution, used as the
            overlay's base layer.
        dst: Destination tensor for the NPU input (letterboxed RGB).
        canvas: RGBA canvas tensor written by ``draw_decoded_masks``.
        decoder: edgefirst-decoder Decoder used for NMS + proto extraction.
        output_tensors: Raw NPU output tensors fed into the decoder.
        letterbox_norm: Normalized letterbox offsets passed to mask
            materialization.
        n_iter: Number of timed iterations to run.
        color_mode: Segmentation mask color assignment — matches the
            ``--color-mode`` flag (class, instance, or track).
    """
    pre_ms, inf_ms, npu_ms, din_ms, dout_ms = [], [], [], [], []
    dec_ms, mat_ms, draw_ms = [], [], []

    for _ in range(n_iter):
        # Preprocess: GPU letterbox-resize frame → NPU input tensor (DMA-BUF)
        t0 = time.monotonic()
        processor.convert(frame, dst, letterbox=(114, 114, 114, 255))
        t1 = time.monotonic()

        # Inference: NPU execution (includes DMA input upload + output download)
        timing = model.run()
        t2 = time.monotonic()

        # Step 1 — Decode: NMS + dequant
        boxes, scores, classes, proto_data = decoder.decode_proto(output_tensors)
        t3 = time.monotonic()

        # Step 2 — Materialize: CPU dot-product → per-detection bitmaps
        masks = (processor.materialize_masks(boxes, scores, classes, proto_data,
                                             letterbox=letterbox_norm)
                 if proto_data else [])
        t4 = time.monotonic()

        # Step 3 — Draw: GL overlay of bitmaps onto canvas
        processor.draw_decoded_masks(canvas, boxes, scores, classes,
                                     seg=masks, background=background,
                                     letterbox=letterbox_norm,
                                     color_mode=color_mode)
        t5 = time.monotonic()

        pre_ms.append((t1 - t0) * 1000)
        inf_ms.append((t2 - t1) * 1000)
        npu_ms.append(timing.run_time_us / 1000)
        din_ms.append(timing.input_time_us / 1000)
        dout_ms.append(timing.output_time_us / 1000)
        dec_ms.append((t3 - t2) * 1000)
        mat_ms.append((t4 - t3) * 1000)
        draw_ms.append((t5 - t4) * 1000)

    total_ms = [pre_ms[i] + inf_ms[i] + dec_ms[i] + mat_ms[i] + draw_ms[i]
                for i in range(n_iter)]

    print(f"\n--- Benchmark ({n_iter} iterations) ---")
    print(f"  {'':30} {'mean':>6}  {'min':>6}  {'max':>6}  {'std':>6}")
    _row("GPU preprocess (convert):", pre_ms)
    _row("Inference (wall clock):", inf_ms)
    _row("  NPU execution:", npu_ms)
    _row("  DMA input upload:", din_ms)
    _row("  DMA output download:", dout_ms)
    _row("Decode (NMS+proto):", dec_ms)
    _row("Materialize (CPU dot-prod):", mat_ms)
    _row("Draw (GL overlay):", draw_ms)
    print(f"  {'─' * 54}")
    _row("Total pipeline:", total_ms)
    mean_total = np.mean(total_ms)
    print(f"  Throughput: {1000 / mean_total:.1f} FPS")


# ── COCO labels (fallback when DVM has no embedded labels) ────────────────────

COCO_LABELS = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train",
    "truck", "boat", "traffic light", "fire hydrant", "stop sign",
    "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep",
    "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
    "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard",
    "sports ball", "kite", "baseball bat", "baseball glove", "skateboard",
    "surfboard", "tennis racket", "bottle", "wine glass", "cup", "fork",
    "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
    "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair",
    "couch", "potted plant", "bed", "dining table", "toilet", "tv",
    "laptop", "mouse", "remote", "keyboard", "cell phone", "microwave",
    "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase",
    "scissors", "teddy bear", "hair drier", "toothbrush",
]


if __name__ == "__main__":
    main()
