// SPDX-FileCopyrightText: Copyright 2025 Au-Zone Technologies
// SPDX-License-Identifier: Apache-2.0

//! # YOLOv8 Inference on ARA-2 NPU
//!
//! End-to-end detection and instance segmentation on the ARA-2 NPU, using the
//! EdgeFirst HAL for GPU preprocessing, decoding, and overlay rendering.
//!
//! ## Pipeline
//!
//! ```text
//! JPEG → [GPU] letterbox resize → PlanarRGB → [NPU] inference
//!                                                      │
//!                                              ┌───────┴────────┐
//!                                         boxes/scores      proto data
//!                                              │                │
//!                                    [1] decode_proto           │
//!                                      NMS + dequant            │
//!                                              │                │
//!                                    [2] materialize_masks ─────┘
//!                                      CPU dot-product
//!                                      coeff × protos → bitmaps
//!                                              │
//!                                    [3] draw_decoded_masks
//!                                      GL overlay onto canvas
//! ```
//!
//! ## Usage
//!
//! See `yolov8 --help` for the full flag reference (generated by clap).
//!
//! ## Features
//!
//! - Automatic detection vs segmentation from DVM metadata or output shapes
//! - Letterbox resize preserving aspect ratio (YOLO gray padding)
//! - DMA-backed intermediate tensors for zero-copy GPU → NPU data transfer
//! - HAL Decoder with automatic dequantization and NMS
//! - Per-stage timing: preprocess / inference / decode / materialize / draw
//! - COCO class labels as fallback when DVM metadata has no labels

use ara2::{Session, dvm_metadata};
use clap::{Parser, ValueEnum};
use edgefirst_hal::{
    codec::{DecodeOptions, ImageDecoder, ImageLoad as _, peek_info},
    decoder::{
        DecoderBuilder, DetectBox, ProtoData, Segmentation,
        configs::{self, DecoderType, DimName, QuantTuple},
    },
    image::{
        ColorMode, Crop, Flip, ImageProcessor, ImageProcessorTrait as _, MaskOverlay,
        MaskResolution, Rect, Rotation, save_jpeg,
    },
    tensor::{DType, PixelFormat, PlaneDescriptor, TensorDyn, TensorMemory, TensorTrait as _},
};
use std::os::fd::AsFd as _;
use std::{path::PathBuf, time::Instant};

// ── Arguments ────────────────────────────────────────────────────────────────

/// Static-image YOLOv8 detection / instance segmentation on the ARA-2 NPU.
#[derive(Parser)]
struct Args {
    /// Path to the compiled DVM model file (e.g. `yolov8n-seg.dvm`).
    model: PathBuf,

    /// Path to the input JPEG/PNG image.
    image: PathBuf,

    /// Save the annotated overlay next to the input as `<image>_overlay.jpg`.
    #[arg(long)]
    save: bool,

    /// Minimum confidence score for detections.
    // Lower default (0.25) than the live example (0.50): static-image
    // inspection benefits from surfacing lower-confidence detections
    // alongside high-confidence ones for visual review.
    #[arg(long, default_value_t = 0.25)]
    threshold: f32,

    /// IoU threshold for non-maximum suppression.
    #[arg(long, default_value_t = 0.45)]
    iou: f32,

    /// Run N benchmark iterations after the single inference and print timing statistics.
    #[arg(long, default_value_t = 0)]
    benchmark: usize,

    /// Segmentation mask color assignment.
    #[arg(long, value_enum, default_value_t = ColorModeArg::Class)]
    color_mode: ColorModeArg,

    /// UNIX socket path for the ARA-2 proxy service.
    #[arg(long, default_value_t = ara2::DEFAULT_SOCKET.to_string())]
    socket: String,
}

/// How segmentation mask colors are assigned.
///
/// This is a command-line mirror of [`ColorMode`] from `edgefirst-hal`.
#[derive(Clone, Copy, Debug, ValueEnum)]
enum ColorModeArg {
    /// One color per class label. Same label → same color across frames.
    Class,
    /// One color per detected instance, cycling per frame.
    Instance,
    /// One color per track ID (requires a tracking-enabled pipeline).
    Track,
}

impl From<ColorModeArg> for ColorMode {
    fn from(v: ColorModeArg) -> Self {
        match v {
            ColorModeArg::Class => ColorMode::Class,
            ColorModeArg::Instance => ColorMode::Instance,
            ColorModeArg::Track => ColorMode::Track,
        }
    }
}

// ── COCO labels (fallback) ───────────────────────────────────────────────────

const COCO: &[&str] = &[
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
];

// ── Output identification ────────────────────────────────────────────────────

/// Whether this model performs detection only or detection + segmentation.
#[derive(Debug, Clone, Copy, PartialEq)]
enum Task {
    Detect,
    Segment,
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/// Normalize an ARA-2 output shape for the HAL decoder.
///
/// ARA-2's FFI struct always reports 3 dimensions `[nch, height, width]`.
/// For logically 2D outputs (e.g. scores `[80, 8400]`), the struct pads
/// width=1, producing `[80, 8400, 1]`. We strip that trailing 1 to recover
/// the true rank.
///
/// The HAL decoder expects an ONNX-style leading batch dimension (it slices
/// `[0, .., ..]` internally to remove it), so we prepend batch=1.
///
/// Examples:
///   `[80, 8400, 1]` → `[1, 80, 8400]`  (scores)
///   `[4, 8400, 1]`  → `[1, 4, 8400]`   (boxes)
///   `[32, 160, 160]` → `[1, 32, 160, 160]` (protos — no trailing 1 to strip)
fn normalize_shape(raw: [usize; 3]) -> Vec<usize> {
    let mut shape: Vec<usize> = raw.to_vec();
    while shape.len() > 1 && shape.last() == Some(&1) {
        shape.pop();
    }
    shape.insert(0, 1);
    shape
}

/// Strip trailing 1s from a metadata shape (Vec<i64>) and widen to usize.
///
/// Metadata declares shapes with the leading batch and any trailing
/// `padding` axes; the NPU runtime strips trailing 1s before returning
/// the per-output shape. Normalising both sides the same way lets us
/// match a runtime shape to its [`dvm_metadata::OutputSpec`].
fn strip_trailing_ones_i64(raw: &[i64]) -> Vec<usize> {
    let mut shape: Vec<usize> = raw.iter().map(|&d| d as usize).collect();
    while shape.len() > 1 && shape.last() == Some(&1) {
        shape.pop();
    }
    shape
}

/// Identify detection output indices: boxes `[1, 4, N]` and scores `[1, C, N]`.
///
/// Box tensors are identified by `shape[1] == 4` (the 4 box coordinates),
/// not by checking whether 4 appears anywhere in the shape — which would
/// misidentify score tensors from 4-class models.
fn identify_det_outputs(shapes: &[Vec<usize>]) -> Result<(usize, usize), String> {
    if shapes.len() < 2 {
        return Err(format!(
            "detection needs >= 2 outputs, got {}",
            shapes.len()
        ));
    }
    let (mut boxes, mut scores) = (None, None);
    for (i, s) in shapes.iter().enumerate() {
        if s.len() == 3 && s[1] == 4 {
            boxes = Some(i);
        } else if s.len() == 3 && scores.is_none() {
            scores = Some(i);
        }
        // Skip rank-4 tensors (proto tensors from seg models)
    }
    Ok((
        boxes.ok_or("cannot identify boxes output (shape[1] == 4)")?,
        scores.ok_or("cannot identify scores output")?,
    ))
}

/// Identify segmentation output indices: boxes, scores, mask_coeff, protos.
///
/// Protos are identified by rank-4 shape `[1, 32, H, W]`.
/// Boxes by `shape[1] == 4`. Mask coefficients by `shape[1] == 32`.
fn identify_seg_outputs(shapes: &[Vec<usize>]) -> Result<(usize, usize, usize, usize), String> {
    if shapes.len() < 4 {
        return Err(format!(
            "segmentation needs 4 outputs, got {}",
            shapes.len()
        ));
    }
    let (mut scores, mut boxes, mut masks, mut protos) = (None, None, None, None);
    for (i, s) in shapes.iter().enumerate() {
        if s.len() == 4 {
            protos = Some(i); // [1, 32, H, W]
        } else if s.len() == 3 && s[1] == 4 {
            boxes = Some(i); // [1, 4, num_boxes]
        } else if s.len() == 3
            && masks.is_none()
            && protos.is_some_and(|p| shapes[p].get(1) == s.get(1))
        {
            masks = Some(i); // [1, 32, num_boxes]
        } else if scores.is_none() {
            scores = Some(i);
        }
    }
    // Retry mask detection: needed when the proto tensor appears after the mask-coeff
    // tensor in the output list (ARA-2 compiler output ordering is not guaranteed).
    if masks.is_none()
        && let Some(pi) = protos
    {
        for (i, s) in shapes.iter().enumerate() {
            if s.len() == 3
                && s[1] != 4
                && Some(i) != scores
                && Some(i) != boxes
                && shapes[pi].get(1) == s.get(1)
            {
                masks = Some(i);
                break;
            }
        }
    }
    Ok((
        boxes.ok_or("cannot identify boxes")?,
        scores.ok_or("cannot identify scores")?,
        masks.ok_or("cannot identify mask_coeff")?,
        protos.ok_or("cannot identify protos")?,
    ))
}

/// Build a canonical Ultralytics `dshape` for a role, used when the DVM
/// did not ship an `edgefirst.json` (e.g. Kinara-1.2.1 official models) or
/// when the metadata entry for that output was missing.
///
/// The HAL decoder treats an empty `dshape` as "shape is already in
/// canonical order"; this is true for boxes / scores / mask coefficients,
/// but for protos the canonical order is NHWC while NPU outputs are NCHW,
/// so the materializer would otherwise mis-identify `num_protos`.
fn canonical_dshape(role: OutputRole, shape: &[usize]) -> Vec<(DimName, usize)> {
    let names: &[DimName] = match role {
        OutputRole::Detection => &[DimName::Batch, DimName::NumFeatures, DimName::NumBoxes],
        OutputRole::Boxes => &[DimName::Batch, DimName::BoxCoords, DimName::NumBoxes],
        OutputRole::Scores => &[DimName::Batch, DimName::NumClasses, DimName::NumBoxes],
        OutputRole::MaskCoefficients => &[DimName::Batch, DimName::NumProtos, DimName::NumBoxes],
        OutputRole::Protos => &[
            DimName::Batch,
            DimName::NumProtos,
            DimName::Height,
            DimName::Width,
        ],
    };
    // Pair element-wise; if the runtime rank is shorter than the canonical
    // names list (e.g. a `padding=1` axis was stripped) the zip stops at the
    // shorter side, which keeps `dshape.len() == shape.len()` as the HAL
    // decoder's validator requires.
    shape
        .iter()
        .copied()
        .zip(names.iter().copied())
        .map(|(n, name)| (name, n))
        .collect()
}

#[derive(Clone, Copy)]
enum OutputRole {
    Detection,
    Boxes,
    Scores,
    MaskCoefficients,
    Protos,
}

/// Return `dshapes[i]` if it was populated from metadata, otherwise the
/// canonical Ultralytics dshape for the role at `shape`.
fn dshape_or_canonical(
    dshapes: &[Vec<(DimName, usize)>],
    i: usize,
    role: OutputRole,
    shape: &[usize],
) -> Vec<(DimName, usize)> {
    if dshapes[i].is_empty() {
        canonical_dshape(role, shape)
    } else {
        dshapes[i].clone()
    }
}

/// Compute a letterbox [`Crop`] that fits `src` into `dst` preserving aspect
/// ratio, centered with YOLO gray (114, 114, 114) padding.
#[allow(
    clippy::cast_precision_loss,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss
)]
fn compute_letterbox(src_w: usize, src_h: usize, dst_w: usize, dst_h: usize) -> Crop {
    let scale = (dst_w as f32 / src_w as f32).min(dst_h as f32 / src_h as f32);
    let new_w = (src_w as f32 * scale) as usize;
    let new_h = (src_h as f32 * scale) as usize;
    Crop::new()
        .with_dst_rect(Some(Rect::new(
            (dst_w - new_w) / 2,
            (dst_h - new_h) / 2,
            new_w,
            new_h,
        )))
        .with_dst_color(Some([114, 114, 114, 255]))
}

fn bench_row(label: &str, data: &[f64]) {
    let n = data.len() as f64;
    let mean = data.iter().sum::<f64>() / n;
    let min = data.iter().cloned().fold(f64::INFINITY, f64::min);
    let max = data.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
    let variance = data.iter().map(|x| (x - mean).powi(2)).sum::<f64>() / n;
    let std = variance.sqrt();
    println!("  {label:<30} {mean:6.2}  {min:6.2}  {max:6.2}  {std:6.2}");
}

// ── Main ─────────────────────────────────────────────────────────────────────

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();
    let color_mode: ColorMode = args.color_mode.into();

    // ── 1. Read DVM metadata ─────────────────────────────────────────────
    let dvm_data = std::fs::read(&args.model)?;
    let metadata = dvm_metadata::read_metadata(&dvm_data)?;
    let dvm_labels = dvm_metadata::read_labels(&dvm_data)?;
    let labels: Vec<&str> = if dvm_labels.is_empty() {
        COCO.to_vec()
    } else {
        dvm_labels.iter().map(|s| s.as_str()).collect()
    };

    let task = metadata
        .as_ref()
        .and_then(|m| m.task())
        .map(|t| {
            if t == "segment" {
                Task::Segment
            } else {
                Task::Detect
            }
        })
        .unwrap_or(Task::Detect);

    println!("Task: {task:?}, classes: {}", labels.len());

    // ── 2. Connect to ARA-2 and load model ───────────────────────────────
    let session = Session::create_via_unix_socket(&args.socket)?;
    let endpoint = &session.list_endpoints()?[0];
    println!(
        "Endpoint: {:?}, DRAM free: {:.1} MB",
        endpoint.check_status()?,
        endpoint.dram_statistics()?.free_size as f64 / 1048576.0
    );

    let t0 = Instant::now();
    let mut model = endpoint.load_model_from_file(&args.model)?;
    model.allocate_tensors(Some(TensorMemory::Dma))?;
    println!("Model loaded in {:?}", t0.elapsed());

    let input_shape = model.input_shape(0);
    let (in_c, in_h, in_w) = (input_shape[0], input_shape[1], input_shape[2]);
    println!("Input: {in_c}x{in_h}x{in_w} (CHW)");

    // ── 3. Build HAL Decoder from output tensor metadata ─────────────────
    let input_dim = in_w.max(in_h) as f32;
    let n_outputs = model.n_outputs();

    let mut shapes = Vec::with_capacity(n_outputs);
    let mut quants = Vec::with_capacity(n_outputs);
    let mut dshapes: Vec<Vec<(DimName, usize)>> = Vec::with_capacity(n_outputs);
    let mut normalized_flags: Vec<Option<bool>> = Vec::with_capacity(n_outputs);

    // Index the metadata outputs by their normalized shape so we can attach
    // edgefirst.json fields (dshape, normalized, encoding) to each runtime
    // output. Older .dvm files without these fields still work — runtime
    // info from the NPU continues to drive shape and quantization.
    let meta_by_shape: std::collections::HashMap<Vec<usize>, &dvm_metadata::OutputSpec> =
        metadata
            .as_ref()
            .map(|m| {
                m.outputs
                    .iter()
                    .map(|o| (strip_trailing_ones_i64(&o.shape), o))
                    .collect()
            })
            .unwrap_or_default();

    for i in 0..n_outputs {
        let raw_shape = model.output_shape(i);
        let shape = normalize_shape(raw_shape);
        let info = model.output_info(i)?;
        let spec = meta_by_shape.get(&shape).copied();

        // Pull dshape from metadata if present. Trim trailing dims past
        // the rank of `shape` (covers metadata declaring a `padding=1`
        // axis the NPU strips). Then patch up a known converter bug:
        // some exports declare `num_features` on a `mask_coefs` output
        // when the spec (metadata.md §Output Types) says the channel
        // axis must be `num_protos` for that role. Substitute so the
        // hal decoder's role-specific axis validator accepts the
        // dshape; the converter should be fixed upstream.
        let dshape: Vec<(DimName, usize)> = spec
            .map(|s| {
                let mut d = s.dshape.clone();
                d.truncate(shape.len());
                if s.output_type.as_deref() == Some("mask_coefs") {
                    for (name, _) in d.iter_mut() {
                        if *name == DimName::NumFeatures {
                            *name = DimName::NumProtos;
                        }
                    }
                }
                d
            })
            .unwrap_or_default();

        // The `normalized` flag from metadata applies to box outputs only
        // (per the EdgeFirst metadata spec). Other roles inherit None.
        let normalized = spec.and_then(|s| s.normalized);

        // Box outputs have shape [1, 4, N] — specifically dim[1]==4 for the
        // Ultralytics split format. Older exports that didn't declare
        // `normalized` emit int-encoded pixel coords (0..input_dim) and need
        // the quant scale divided by input_dim to convert to the [0, 1]
        // range the decoder reports back. Newer spec-conforming exports
        // (normalized=true) already emit normalized coords so we use qn as-is.
        let is_box_output = shape.len() == 3 && shape[1] == 4;
        let scale = if is_box_output && normalized.is_none() && input_dim > 1.0 {
            info.quant.qn / input_dim
        } else {
            info.quant.qn
        };
        println!(
            "  output[{i}] shape={shape:?} bpp={} signed={} qn={} offset={} \
             (adj_scale={scale:.6e}) normalized={normalized:?} dshape_len={}",
            info.bpp,
            info.quant.is_signed,
            info.quant.qn,
            info.quant.offset,
            dshape.len()
        );
        quants.push((scale, info.quant.offset, info.bpp, info.quant.is_signed));
        shapes.push(shape);
        dshapes.push(dshape);
        normalized_flags.push(normalized);
    }

    // Override task if output shapes indicate segmentation (rank-4 proto tensor present).
    // Some DVM files report "detect" even for segmentation models.
    let task = if task == Task::Detect && shapes.iter().any(|s| s.len() == 4) {
        println!("  (task overridden to Segment based on output shapes)");
        Task::Segment
    } else {
        task
    };

    // For box outputs, prefer the metadata's normalized flag; if absent,
    // assume true (legacy converters that pre-divided the scale by
    // input_dim above are now operating in the normalized domain too).
    let normalized_for = |i: usize| Some(normalized_flags[i].unwrap_or(true));

    let decoder = match (task, n_outputs) {
        // Monolithic detection: single output [1, nc+4, N] with normalized boxes
        (Task::Detect, 1) => {
            println!("  Layout: monolithic detection [{:?}]", shapes[0]);
            DecoderBuilder::new()
                .with_config_yolo_det(
                    configs::Detection {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[0].0, quants[0].1)),
                        shape: shapes[0].clone(),
                        dshape: dshape_or_canonical(&dshapes, 0, OutputRole::Detection, &shapes[0]),
                        normalized: normalized_for(0),
                        ..Default::default()
                    },
                    None,
                )
                .with_score_threshold(args.threshold)
                .with_iou_threshold(args.iou)
                .build()?
        }
        // Split detection: separate boxes [1,4,N] + scores [1,nc,N]
        (Task::Detect, _) => {
            let (bi, si) = identify_det_outputs(&shapes)?;
            println!("  Layout: split detection (boxes[{bi}] + scores[{si}])");
            DecoderBuilder::new()
                .with_config_yolo_split_det(
                    configs::Boxes {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[bi].0, quants[bi].1)),
                        shape: shapes[bi].clone(),
                        dshape: dshape_or_canonical(&dshapes, bi, OutputRole::Boxes, &shapes[bi]),
                        normalized: normalized_for(bi),
                        ..Default::default()
                    },
                    configs::Scores {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[si].0, quants[si].1)),
                        shape: shapes[si].clone(),
                        dshape: dshape_or_canonical(&dshapes, si, OutputRole::Scores, &shapes[si]),
                        ..Default::default()
                    },
                )
                .with_score_threshold(args.threshold)
                .with_iou_threshold(args.iou)
                .build()?
        }
        (Task::Segment, _) => {
            let (bi, si, mi, pi) = identify_seg_outputs(&shapes)?;
            DecoderBuilder::new()
                .with_config_yolo_split_segdet(
                    configs::Boxes {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[bi].0, quants[bi].1)),
                        shape: shapes[bi].clone(),
                        dshape: dshape_or_canonical(&dshapes, bi, OutputRole::Boxes, &shapes[bi]),
                        normalized: normalized_for(bi),
                        ..Default::default()
                    },
                    configs::Scores {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[si].0, quants[si].1)),
                        shape: shapes[si].clone(),
                        dshape: dshape_or_canonical(&dshapes, si, OutputRole::Scores, &shapes[si]),
                        ..Default::default()
                    },
                    configs::MaskCoefficients {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[mi].0, quants[mi].1)),
                        shape: shapes[mi].clone(),
                        dshape: dshape_or_canonical(
                            &dshapes,
                            mi,
                            OutputRole::MaskCoefficients,
                            &shapes[mi],
                        ),
                        ..Default::default()
                    },
                    configs::Protos {
                        decoder: DecoderType::Ultralytics,
                        quantization: Some(QuantTuple(quants[pi].0, quants[pi].1)),
                        shape: shapes[pi].clone(),
                        dshape: dshape_or_canonical(&dshapes, pi, OutputRole::Protos, &shapes[pi]),
                        ..Default::default()
                    },
                )
                .with_score_threshold(args.threshold)
                .with_iou_threshold(args.iou)
                .build()?
        }
    };

    println!("Decoder: {:?}", decoder.model_type());

    // ── 4. Load image and set up preprocessing ───────────────────────────
    let image_bytes = std::fs::read(&args.image)?;
    let mut processor = ImageProcessor::new()?;

    // Decode JPEG into a pre-allocated DMA tensor for GPU access.
    let opts = DecodeOptions::default().with_format(PixelFormat::Rgba);
    let info = peek_info(&image_bytes, &opts)?;
    let (img_w, img_h) = (info.width, info.height);
    println!("Image: {img_w}x{img_h}");
    let mut src = processor.create_image(img_w, img_h, PixelFormat::Rgba, DType::U8, None)?;
    let mut img_decoder = ImageDecoder::new();
    src.load_image(&mut img_decoder, &image_bytes, &opts)?;

    let input_quant = model.input_quants(0);
    let input_dtype = if input_quant.is_signed {
        DType::I8
    } else {
        DType::U8
    };

    let input_fd = model.input_tensor(0).clone_fd()?;
    let plane = PlaneDescriptor::new(input_fd.as_fd())?;
    let mut dst =
        processor.import_image(plane, None, in_w, in_h, PixelFormat::PlanarRgb, input_dtype)?;

    // Letterbox: fit src into model input preserving aspect ratio with gray padding.
    let letterbox = compute_letterbox(img_w, img_h, in_w, in_h);
    let letterbox_norm = MaskOverlay::default()
        .with_letterbox_crop(&letterbox, in_w, in_h)
        .letterbox;

    // ── 5. Pre-allocate render canvas ───────────────────────────────────
    // Canvas at source image dimensions for display-resolution overlay.
    // src doubles as the background for the mask overlay blit.
    let mut canvas = processor.create_image(img_w, img_h, PixelFormat::Rgba, DType::U8, None)?;

    // ── 5b. Pre-allocate output tensor wrappers ──────────────────────────
    // Wrap the model's DMA output buffers directly — no per-frame CPU copy.
    let output_tensors: Vec<TensorDyn> = (0..n_outputs)
        .map(|i| {
            let dtype = match (quants[i].2, quants[i].3) {
                (1, false) => DType::U8,
                (1, true) => DType::I8,
                (2, false) => DType::U16,
                (2, true) => DType::I16,
                _ => panic!("unsupported bpp={} signed={}", quants[i].2, quants[i].3),
            };
            let fd = model.output_tensor(i).clone_fd().expect("clone output fd");
            TensorDyn::from_fd(fd, &shapes[i], dtype, None).expect("wrap output tensor")
        })
        .collect();
    let output_refs: Vec<&TensorDyn> = output_tensors.iter().collect();

    // ── 6. Warmup ────────────────────────────────────────────────────────
    processor.convert(&src, &mut dst, Rotation::None, Flip::None, letterbox)?;
    model.run()?;

    // ── 7. Inference ─────────────────────────────────────────────────────
    let t_pre = Instant::now();
    processor.convert(&src, &mut dst, Rotation::None, Flip::None, letterbox)?;
    let preprocess_time = t_pre.elapsed();

    let t_inf = Instant::now();
    let timing = model.run()?;
    let inference_time = t_inf.elapsed();

    // ── 8. Decode → Materialize → Draw ───────────────────────────────────
    //
    // Step 1 — Decode: run NMS on the raw NPU output tensors, dequantize
    // scores and boxes, and extract the proto data (prototype tensor +
    // per-detection mask coefficients) needed for segmentation.
    let mut detections: Vec<DetectBox> = Vec::with_capacity(100);
    let t_decode = Instant::now();
    let proto: Option<ProtoData> = decoder
        .decode_proto(&output_refs, &mut detections)
        .map_err(|e| format!("decode_proto: {e:#?}"))?;
    let decode_time = t_decode.elapsed();

    // Step 2 — Materialize: CPU dot-product of per-detection mask coefficients
    // [N×32] against the shared proto tensor [32×160×160], yielding one binary
    // bitmap per detection in output-image space. No-op for detection-only models.
    let t_mat = Instant::now();
    let masks: Vec<Segmentation> = if let Some(ref proto_data) = proto {
        processor.materialize_masks(
            &detections,
            proto_data,
            letterbox_norm,
            MaskResolution::Proto,
        )?
    } else {
        Vec::new()
    };
    let materialize_time = t_mat.elapsed();

    // Step 3 — Draw: GL-accelerated rendering of each binary mask as a colored
    // overlay quad, composited over the background image on the canvas.
    let overlay = MaskOverlay::default()
        .with_background(&src)
        .with_letterbox_crop(&letterbox, in_w, in_h)
        .with_color_mode(color_mode);
    let t_draw = Instant::now();
    processor.draw_decoded_masks(&mut canvas, &detections, &masks, overlay)?;
    let draw_time = t_draw.elapsed();

    // ── 9. Print results ─────────────────────────────────────────────────
    println!("\n--- Timing ---");
    println!("  Preprocess:   {:?}", preprocess_time);
    println!(
        "  Inference:    {:?} (npu: {:?}, in: {:?}, out: {:?})",
        inference_time, timing.run_time, timing.input_time, timing.output_time
    );
    println!("  Decode:       {:?}", decode_time);
    println!("  Materialize:  {:?}", materialize_time);
    println!("  Draw:         {:?}", draw_time);
    println!(
        "  Total:        {:?}",
        preprocess_time + inference_time + decode_time + materialize_time + draw_time
    );

    println!("\n--- Detections ({}) ---", detections.len());
    // Decoder produces normalized box coordinates in the letterboxed model
    // input frame (e.g. 640x640).  To map back to the original image we
    // must first un-pad, then rescale by 1/letterbox_scale.
    let letterbox_scale = (in_w as f32 / img_w as f32).min(in_h as f32 / img_h as f32);
    let new_w = img_w as f32 * letterbox_scale;
    let new_h = img_h as f32 * letterbox_scale;
    let pad_x = (in_w as f32 - new_w) / 2.0;
    let pad_y = (in_h as f32 - new_h) / 2.0;
    for det in &detections {
        let name = labels.get(det.label).unwrap_or(&"?");
        // Normalized letterbox coords -> letterbox pixels
        let lx1 = det.bbox.xmin * in_w as f32;
        let ly1 = det.bbox.ymin * in_h as f32;
        let lx2 = det.bbox.xmax * in_w as f32;
        let ly2 = det.bbox.ymax * in_h as f32;
        // Remove padding and rescale to original image pixels
        let x1 = ((lx1 - pad_x) / letterbox_scale).max(0.0);
        let y1 = ((ly1 - pad_y) / letterbox_scale).max(0.0);
        let x2 = ((lx2 - pad_x) / letterbox_scale).min(img_w as f32);
        let y2 = ((ly2 - pad_y) / letterbox_scale).min(img_h as f32);
        println!(
            "  {name:>12} ({:2}): {:5.1}%  [{:.0}, {:.0}, {:.0}, {:.0}]",
            det.label,
            det.score * 100.0,
            x1,
            y1,
            x2,
            y2
        );
    }

    // ── 10. Benchmark ────────────────────────────────────────────────────
    if args.benchmark > 0 {
        // Full-pipeline warmup: prime GPU caches, JIT paths, and EGL image
        // bindings before timing begins. Runs the complete decode → materialize
        // → draw sequence so all steady-state paths are warm.
        {
            let mut warmup_boxes = Vec::with_capacity(100);
            processor.convert(&src, &mut dst, Rotation::None, Flip::None, letterbox)?;
            model.run()?;
            let proto = decoder
                .decode_proto(&output_refs, &mut warmup_boxes)
                .map_err(|e| format!("decode_proto: {e:#?}"))?;
            let masks: Vec<Segmentation> = if let Some(ref pd) = proto {
                processor.materialize_masks(
                    &warmup_boxes,
                    pd,
                    letterbox_norm,
                    MaskResolution::Proto,
                )?
            } else {
                Vec::new()
            };
            let overlay = MaskOverlay::default()
                .with_background(&src)
                .with_letterbox_crop(&letterbox, in_w, in_h)
                .with_color_mode(color_mode);
            processor.draw_decoded_masks(&mut canvas, &warmup_boxes, &masks, overlay)?;
        }

        let n = args.benchmark;
        let mut pre_ms = Vec::with_capacity(n);
        let mut inf_ms = Vec::with_capacity(n);
        let mut npu_ms = Vec::with_capacity(n);
        let mut din_ms = Vec::with_capacity(n);
        let mut dout_ms = Vec::with_capacity(n);
        let mut decode_ms = Vec::with_capacity(n);
        let mut mat_ms = Vec::with_capacity(n);
        let mut draw_ms = Vec::with_capacity(n);

        // `boxes` is declared outside the loop so its backing allocation is
        // reused across iterations; `boxes.clear()` resets length without
        // freeing memory.
        let mut boxes = Vec::with_capacity(100);

        for _ in 0..n {
            // Preprocess: GPU letterbox-resize src → NPU input tensor (DMA-BUF).
            let t0 = Instant::now();
            processor.convert(&src, &mut dst, Rotation::None, Flip::None, letterbox)?;
            let t1 = Instant::now();

            // Inference: NPU execution (includes DMA upload/download).
            let t = model.run()?;
            let t2 = Instant::now();

            // Step 1 — Decode: NMS + dequant on NPU output tensors.
            boxes.clear();
            let proto = decoder
                .decode_proto(&output_refs, &mut boxes)
                .map_err(|e| format!("decode_proto: {e:#?}"))?;
            let t3 = Instant::now();

            // Step 2 — Materialize: CPU dot-product → per-detection bitmaps.
            let masks: Vec<Segmentation> = if let Some(ref proto_data) = proto {
                processor.materialize_masks(
                    &boxes,
                    proto_data,
                    letterbox_norm,
                    MaskResolution::Proto,
                )?
            } else {
                Vec::new()
            };
            let t4 = Instant::now();

            // Step 3 — Draw: GL overlay of bitmaps onto canvas.
            // MaskOverlay is a lightweight builder with no heap allocation.
            let overlay = MaskOverlay::default()
                .with_background(&src)
                .with_letterbox_crop(&letterbox, in_w, in_h)
                .with_color_mode(color_mode);
            processor.draw_decoded_masks(&mut canvas, &boxes, &masks, overlay)?;
            let t5 = Instant::now();

            pre_ms.push((t1 - t0).as_micros() as f64 / 1000.0);
            inf_ms.push((t2 - t1).as_micros() as f64 / 1000.0);
            npu_ms.push(t.run_time.as_micros() as f64 / 1000.0);
            din_ms.push(t.input_time.as_micros() as f64 / 1000.0);
            dout_ms.push(t.output_time.as_micros() as f64 / 1000.0);
            decode_ms.push((t3 - t2).as_micros() as f64 / 1000.0);
            mat_ms.push((t4 - t3).as_micros() as f64 / 1000.0);
            draw_ms.push((t5 - t4).as_micros() as f64 / 1000.0);
        }

        println!("\n--- Benchmark ({n} iterations) ---");
        println!(
            "  {:30} {:>7}  {:>7}  {:>7}  {:>7}",
            "", "mean", "min", "max", "std"
        );
        bench_row("GPU preprocess (convert):", &pre_ms);
        bench_row("Inference (wall clock):", &inf_ms);
        bench_row("  NPU execution:", &npu_ms);
        bench_row("  DMA input upload:", &din_ms);
        bench_row("  DMA output download:", &dout_ms);
        bench_row("Decode (NMS+proto):", &decode_ms);
        bench_row("Materialize (CPU dot-prod):", &mat_ms);
        bench_row("Draw (GL overlay):", &draw_ms);
        let total_ms: Vec<f64> = (0..n)
            .map(|i| pre_ms[i] + inf_ms[i] + decode_ms[i] + mat_ms[i] + draw_ms[i])
            .collect();
        println!("  {}", "─".repeat(54));
        bench_row("Total pipeline:", &total_ms);
        let mean_total: f64 = total_ms.iter().sum::<f64>() / n as f64;
        println!("  Throughput: {:.1} FPS", 1000.0 / mean_total);
    }

    // ── 11. Save overlay ─────────────────────────────────────────────────
    if args.save {
        let stem = args.image.file_stem().unwrap_or_default().to_string_lossy();
        let out_path = args.image.with_file_name(format!("{stem}_overlay.jpg"));
        save_jpeg(&canvas, out_path.to_str().unwrap(), 95)?;
        println!("\n  Saved: {}", out_path.display());
    }

    Ok(())
}
