#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2025 Au-Zone Technologies
# SPDX-License-Identifier: Apache-2.0
"""
YOLOv8 detection + instance segmentation on ARA-2 NPU.

End-to-end inference using the same 3-step postprocessing pipeline as
the Rust example (examples/yolov8.rs):

    JPEG → [GPU] letterbox resize → PlanarRGB → [NPU] inference
                                                         │
                                                 ┌───────┴────────┐
                                            boxes/scores      proto data
                                                 │                │
                                       [1] decode_proto           │
                                         NMS + dequant            │
                                                 │                │
                                       [2] materialize_masks ─────┘
                                         CPU dot-product
                                         coeff × protos → bitmaps
                                                 │
                                       [3] draw_decoded_masks
                                         GL overlay onto canvas

Usage:
    Run with ``--help`` for the full flag reference (generated by argparse).

Requirements:
    edgefirst-ara2  edgefirst-hal  numpy
"""

from __future__ import annotations

import argparse
import os
import sys
import time

import numpy as np

import edgefirst_ara2 as ara2
import edgefirst_hal as hal


# ── Helpers ───────────────────────────────────────────────────────────────────


def normalize_shape(raw: tuple[int, int, int]) -> list[int]:
    """Normalize an ARA-2 output shape for the HAL decoder.

    ARA-2 always reports 3D shapes [C, H, W]. For logically 2D outputs
    (e.g., scores [80, 8400]), the shape is padded as [80, 8400, 1].
    We strip trailing 1s and prepend batch=1 for the decoder.

      [80, 8400, 1]  → [1, 80, 8400]     (scores)
      [4, 8400, 1]   → [1, 4, 8400]      (boxes)
      [32, 160, 160] → [1, 32, 160, 160] (protos)
    """
    shape = list(raw)
    while len(shape) > 1 and shape[-1] == 1:
        shape.pop()
    shape.insert(0, 1)
    return shape


def compute_letterbox(
    src_w: int, src_h: int, dst_w: int, dst_h: int
) -> tuple[hal.Rect, tuple[float, float, float, float]]:
    """Fit src into dst preserving aspect ratio with YOLO gray (114) padding.

    Returns:
        dst_rect:      pixel-space Rect for ImageProcessor.convert()
        letterbox_norm: normalized (lx0, ly0, lx1, ly1) for materialize_masks
                        and draw_decoded_masks
    """
    scale = min(dst_w / src_w, dst_h / src_h)
    new_w = int(src_w * scale)
    new_h = int(src_h * scale)
    x = (dst_w - new_w) // 2
    y = (dst_h - new_h) // 2
    rect = hal.Rect(x, y, new_w, new_h)
    norm = (x / dst_w, y / dst_h, (x + new_w) / dst_w, (y + new_h) / dst_h)
    return rect, norm


def output_dtype(bpp: int, signed: bool) -> str:
    """Map ARA-2 output tensor bpp/signed flags to a HAL dtype string."""
    if bpp == 1:
        return "int8" if signed else "uint8"
    return "int16" if signed else "uint16"


def build_decoder(
    shapes: list[list[int]],
    quants: list,
    input_dim: float,
    threshold: float,
    iou: float,
) -> hal.Decoder:
    """Build a HAL Decoder from model output metadata.

    Output tensor roles are identified by shape:
      - Protos:             rank-4  [1, 32, H, W]
      - Boxes:              rank-3  [1,  4, N]  (shape[1] == 4)
      - Mask coefficients:  rank-3  [1, 32, N]  (shape[1] == n_proto_channels)
      - Scores:             rank-3  [1,  C, N]  (everything else)
    """
    # Number of prototype channels (e.g., 32) from the rank-4 proto tensor.
    proto_shape = next((s for s in shapes if len(s) == 4), None)
    n_proto_ch = proto_shape[1] if proto_shape else None

    outputs = []
    for i, shape in enumerate(shapes):
        qn, offset = quants[i].qn, quants[i].offset

        if len(shape) == 4:
            # Proto tensor [1, 32, H, W]
            out = hal.Output.protos(shape=shape, decoder=hal.DecoderType.Ultralytics)
            out = out.with_quantization(qn, offset)

        elif len(shape) == 3 and shape[1] == 4:
            # Box tensor [1, 4, N] — divide qn by input_dim to normalize to [0, 1]
            scale = qn / input_dim if input_dim > 1 else qn
            out = hal.Output.boxes(shape=shape, decoder=hal.DecoderType.Ultralytics)
            out = out.with_quantization(scale, offset).with_normalized(True)

        elif n_proto_ch and len(shape) == 3 and shape[1] == n_proto_ch:
            # Mask coefficient tensor [1, 32, N]
            out = hal.Output.mask_coefficients(shape=shape,
                                               decoder=hal.DecoderType.Ultralytics)
            out = out.with_quantization(qn, offset)

        else:
            # Score tensor [1, C, N]
            out = hal.Output.scores(shape=shape, decoder=hal.DecoderType.Ultralytics)
            out = out.with_quantization(qn, offset)

        outputs.append(out)

    return hal.Decoder.new_from_outputs(
        outputs,
        score_threshold=threshold,
        iou_threshold=iou,
        decoder_version=hal.DecoderVersion.Yolov8,
    )


# ── Benchmark stats ───────────────────────────────────────────────────────────


def _row(label: str, data: list[float]) -> None:
    a = np.array(data)
    print(f"  {label:<30} {a.mean():6.2f}  {a.min():6.2f}  {a.max():6.2f}  {a.std():6.2f}")


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="YOLOv8 detection + segmentation on ARA-2 NPU",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("model", help="Path to compiled .dvm model file")
    parser.add_argument("image", help="Path to input image (JPEG/PNG)")
    # Lower default (0.25) than yolov8_live.py (0.50): static-image inspection
    # benefits from surfacing lower-confidence detections for visual review.
    parser.add_argument("--threshold", type=float, default=0.25)
    parser.add_argument("--iou", type=float, default=0.45)
    parser.add_argument("--benchmark", type=int, default=0,
                        help="Run N iterations and print timing statistics")
    parser.add_argument("--save", action="store_true",
                        help="Save overlay image next to the input image")
    parser.add_argument(
        "--color-mode", default="class",
        choices=["class", "instance", "track"],
        help="Segmentation mask color assignment (default: class)",
    )
    parser.add_argument("--socket", default=ara2.DEFAULT_SOCKET)
    args = parser.parse_args()

    # Map --color-mode to the HAL ColorMode enum
    color_mode = {
        "class": hal.ColorMode.Class,
        "instance": hal.ColorMode.Instance,
        "track": hal.ColorMode.Track,
    }[args.color_mode]

    # ── 1. Read DVM metadata ─────────────────────────────────────────────
    print(f"edgefirst-ara2 v{ara2.__version__}, edgefirst-hal v{hal.version()}")
    metadata = ara2.read_metadata(args.model)
    labels = ara2.read_labels(args.model) or COCO_LABELS
    if metadata:
        print(f"Task: {metadata.task}, Classes: {len(labels)}")
        if metadata.compilation and metadata.compilation.ppa:
            ppa = metadata.compilation.ppa
            print(f"Target: {metadata.compilation.target}, "
                  f"IPS: {ppa.ips:.0f}, Power: {ppa.power_mw:.0f} mW")

    # ── 2. Connect to ARA-2 and load model ───────────────────────────────
    session = ara2.Session.create_via_unix_socket(args.socket)
    endpoints = session.list_endpoints()
    if not endpoints:
        print("No ARA-2 endpoints found. Is the proxy running?")
        sys.exit(1)

    endpoint = endpoints[0]
    stats = endpoint.dram_statistics()
    print(f"Endpoint: {endpoint.check_status()}, "
          f"DRAM: {stats.free_size / 1048576:.0f} / {stats.dram_size / 1048576:.0f} MB free")

    with endpoint.load_model(args.model) as model:
        model.allocate_tensors("dma")
        c, h, w = model.input_shape(0)
        input_dim = float(max(w, h))
        iq = model.input_quants(0)
        print(f"Input: {c}×{h}×{w} (CHW), dtype={'int8' if iq.is_signed else 'uint8'}")

        # ── 3. Build decoder from output tensor metadata ─────────────────
        shapes, quants = [], []
        for i in range(model.n_outputs):
            shape = normalize_shape(model.output_shape(i))
            oq = model.output_quants(i)
            info = model.output_info(i)
            print(f"  output[{i}]: {shape}  bpp={info.bpp}  "
                  f"qn={oq.qn:.4f}  signed={oq.is_signed}")
            shapes.append(shape)
            quants.append(oq)

        decoder = build_decoder(shapes, quants, input_dim, args.threshold, args.iou)

        # ── 4. Load source image into a DMA-BUF tensor ───────────────────
        processor = hal.ImageProcessor()
        with open(args.image, "rb") as f:
            jpeg_bytes = f.read()
        src = hal.Tensor.load_from_bytes(
            jpeg_bytes, format=hal.PixelFormat.Rgba, mem=hal.TensorMemory.DMA,
        )
        img_w, img_h = src.width, src.height
        print(f"Image: {img_w}×{img_h}")

        # ── 5. Import NPU input tensor and compute letterbox ──────────────
        # Letterbox-resize src → NPU input preserving aspect ratio with
        # YOLO gray (114, 114, 114) padding. The same letterbox_norm is
        # later passed to materialize_masks and draw_decoded_masks so mask
        # coordinates are correctly mapped to output-image space.
        input_fd = model.input_tensor_fd(0)
        try:
            dst = processor.import_image(
                input_fd, w, h, hal.PixelFormat.PlanarRgb,
                dtype="int8" if iq.is_signed else "uint8",
            )
        finally:
            os.close(input_fd)

        letterbox_rect, letterbox_norm = compute_letterbox(img_w, img_h, w, h)

        # ── 6. Wrap output DMA-BUF tensors for zero-copy decode ──────────
        # These persist across iterations; model.run() updates the underlying
        # DMA memory in-place, so decode_proto always sees fresh data without
        # any CPU copy.
        output_tensors = []
        for i in range(model.n_outputs):
            fd = model.output_tensor_fd(i)
            # from_fd takes ownership of fd via OwnedFd (no dup) — do NOT close.
            t = hal.Tensor.from_fd(fd, shapes[i],
                                   output_dtype(model.output_info(i).bpp,
                                                model.output_quants(i).is_signed))
            output_tensors.append(t)

        # ── 7. Pre-allocate render canvas ────────────────────────────────
        # Blank DMA-BUF RGBA canvas at source-image resolution for the overlay.
        canvas = hal.Tensor.image(img_w, img_h, hal.PixelFormat.Rgba,
                                  hal.TensorMemory.DMA)

        # ── 8. Warmup: prime GPU caches, JIT paths, EGL image bindings ───
        processor.convert(src, dst, dst_crop=letterbox_rect,
                          dst_color=(114, 114, 114, 255))
        model.run()
        _wb, _ws, _wc, _wp = decoder.decode_proto(output_tensors)
        _wm = processor.materialize_masks(_wb, _ws, _wc, _wp,
                                          letterbox=letterbox_norm) if _wp else []
        processor.draw_decoded_masks(canvas, _wb, _ws, _wc, seg=_wm,
                                     background=src, letterbox=letterbox_norm,
                                     color_mode=color_mode)

        # ── 9. Single-shot timed run ──────────────────────────────────────
        t0 = time.monotonic()
        processor.convert(src, dst, dst_crop=letterbox_rect,
                          dst_color=(114, 114, 114, 255))
        pre_ms = (time.monotonic() - t0) * 1000

        t1 = time.monotonic()
        timing = model.run()
        inf_ms = (time.monotonic() - t1) * 1000

        # Step 1 — Decode: NMS + dequant on raw NPU output tensors
        t2 = time.monotonic()
        boxes, scores, classes, proto_data = decoder.decode_proto(output_tensors)
        dec_ms = (time.monotonic() - t2) * 1000

        # Step 2 — Materialize: CPU dot-product coeff × protos → bitmaps.
        # No-op for detection-only models (proto_data is None).
        t3 = time.monotonic()
        masks = (processor.materialize_masks(boxes, scores, classes, proto_data,
                                             letterbox=letterbox_norm)
                 if proto_data else [])
        mat_ms = (time.monotonic() - t3) * 1000

        # Step 3 — Draw: GL-accelerated overlay of bitmaps onto canvas
        t4 = time.monotonic()
        processor.draw_decoded_masks(canvas, boxes, scores, classes,
                                     seg=masks, background=src,
                                     letterbox=letterbox_norm,
                                     color_mode=color_mode)
        draw_ms = (time.monotonic() - t4) * 1000

        # ── 10. Print results ─────────────────────────────────────────────
        n_det = len(scores)
        print(f"\n--- Detections ({n_det}) ---")
        for i in range(n_det):
            cls = int(classes[i])
            name = labels[cls] if cls < len(labels) else f"class_{cls}"
            x1, y1 = boxes[i, 0] * img_w, boxes[i, 1] * img_h
            x2, y2 = boxes[i, 2] * img_w, boxes[i, 3] * img_h
            print(f"  {name:>12} {scores[i]*100:5.1f}%  "
                  f"[{x1:.0f}, {y1:.0f}, {x2:.0f}, {y2:.0f}]")

        total = pre_ms + inf_ms + dec_ms + mat_ms + draw_ms
        print("\n--- Timing ---")
        print(f"  Preprocess:  {pre_ms:6.2f} ms")
        print(f"  Inference:   {inf_ms:6.2f} ms"
              f"  (npu: {timing.run_time_us/1000:.2f} ms,"
              f"  in: {timing.input_time_us/1000:.2f} ms,"
              f"  out: {timing.output_time_us/1000:.2f} ms)")
        print(f"  Decode:      {dec_ms:6.2f} ms")
        print(f"  Materialize: {mat_ms:6.2f} ms")
        print(f"  Draw:        {draw_ms:6.2f} ms")
        print(f"  Total:       {total:6.2f} ms  ({1000/total:.1f} FPS)")

        # ── 11. Save overlay ──────────────────────────────────────────────
        if args.save:
            base, _ = os.path.splitext(args.image)
            out_path = base + "_overlay.jpg"
            canvas.save_jpeg(out_path, 90)
            print(f"\n  Saved: {out_path}")

        # ── 12. Benchmark ─────────────────────────────────────────────────
        if args.benchmark > 0:
            _benchmark(
                model,
                processor=processor,
                src=src,
                dst=dst,
                canvas=canvas,
                decoder=decoder,
                output_tensors=output_tensors,
                letterbox_rect=letterbox_rect,
                letterbox_norm=letterbox_norm,
                n_iter=args.benchmark,
                color_mode=color_mode,
            )


def _benchmark(
    model: ara2.Model,
    *,
    processor: hal.ImageProcessor,
    src: hal.Tensor,
    dst: hal.Tensor,
    canvas: hal.Tensor,
    decoder: hal.Decoder,
    output_tensors: list,
    letterbox_rect: hal.Rect,
    letterbox_norm: tuple,
    n_iter: int,
    color_mode: hal.ColorMode,
) -> None:
    """Run N timed iterations and print per-stage statistics.

    Args:
        model: Loaded ARA-2 model to benchmark.
        processor: HAL ImageProcessor used for convert / draw.
        src: Source image tensor (already populated).
        dst: Destination tensor for the NPU input (letterboxed RGB).
        canvas: RGBA canvas tensor written by ``draw_decoded_masks``.
        decoder: HAL Decoder used for NMS + proto extraction.
        output_tensors: Raw NPU output tensors fed into the decoder.
        letterbox_rect: Pixel-space rect for the letterbox crop.
        letterbox_norm: Normalized letterbox offsets passed to mask
            materialization.
        n_iter: Number of timed iterations to run.
        color_mode: Segmentation mask color assignment — matches the
            ``--color-mode`` flag (class, instance, or track).
    """
    pre_ms, inf_ms, npu_ms, din_ms, dout_ms = [], [], [], [], []
    dec_ms, mat_ms, draw_ms = [], [], []

    for _ in range(n_iter):
        # Preprocess: GPU letterbox-resize src → NPU input tensor (DMA-BUF)
        t0 = time.monotonic()
        processor.convert(src, dst, dst_crop=letterbox_rect,
                          dst_color=(114, 114, 114, 255))
        t1 = time.monotonic()

        # Inference: NPU execution (includes DMA input upload + output download)
        timing = model.run()
        t2 = time.monotonic()

        # Step 1 — Decode: NMS + dequant
        boxes, scores, classes, proto_data = decoder.decode_proto(output_tensors)
        t3 = time.monotonic()

        # Step 2 — Materialize: CPU dot-product → per-detection bitmaps
        masks = (processor.materialize_masks(boxes, scores, classes, proto_data,
                                             letterbox=letterbox_norm)
                 if proto_data else [])
        t4 = time.monotonic()

        # Step 3 — Draw: GL overlay of bitmaps onto canvas
        processor.draw_decoded_masks(canvas, boxes, scores, classes,
                                     seg=masks, background=src,
                                     letterbox=letterbox_norm,
                                     color_mode=color_mode)
        t5 = time.monotonic()

        pre_ms.append((t1 - t0) * 1000)
        inf_ms.append((t2 - t1) * 1000)
        npu_ms.append(timing.run_time_us / 1000)
        din_ms.append(timing.input_time_us / 1000)
        dout_ms.append(timing.output_time_us / 1000)
        dec_ms.append((t3 - t2) * 1000)
        mat_ms.append((t4 - t3) * 1000)
        draw_ms.append((t5 - t4) * 1000)

    total_ms = [pre_ms[i] + inf_ms[i] + dec_ms[i] + mat_ms[i] + draw_ms[i]
                for i in range(n_iter)]

    print(f"\n--- Benchmark ({n_iter} iterations) ---")
    print(f"  {'':30} {'mean':>6}  {'min':>6}  {'max':>6}  {'std':>6}")
    _row("GPU preprocess (convert):", pre_ms)
    _row("Inference (wall clock):", inf_ms)
    _row("  NPU execution:", npu_ms)
    _row("  DMA input upload:", din_ms)
    _row("  DMA output download:", dout_ms)
    _row("Decode (NMS+proto):", dec_ms)
    _row("Materialize (CPU dot-prod):", mat_ms)
    _row("Draw (GL overlay):", draw_ms)
    print(f"  {'─' * 54}")
    _row("Total pipeline:", total_ms)
    mean_total = np.mean(total_ms)
    print(f"  Throughput: {1000 / mean_total:.1f} FPS")


# ── COCO labels (fallback when DVM has no embedded labels) ────────────────────

COCO_LABELS = [
    "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train",
    "truck", "boat", "traffic light", "fire hydrant", "stop sign",
    "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep",
    "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
    "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard",
    "sports ball", "kite", "baseball bat", "baseball glove", "skateboard",
    "surfboard", "tennis racket", "bottle", "wine glass", "cup", "fork",
    "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange",
    "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair",
    "couch", "potted plant", "bed", "dining table", "toilet", "tv",
    "laptop", "mouse", "remote", "keyboard", "cell phone", "microwave",
    "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase",
    "scissors", "teddy bear", "hair drier", "toothbrush",
]


if __name__ == "__main__":
    main()
